### ISSUE TITLE
get_bucket_location returns an empty character vector

### ISSUE THREAD

**Issue by tomsing1** [paws-r/paws#257]
I am not sure if this is the intended behavior, but just in case:

My bucket is located in `us-west-2` and I can get objects by specifying this region in the `s3()` constructor:

```r
s3 <- paws::s3(
    config = list(
      region = 'us-west-2'
    )
  )
```

I can successfully get objects from my bucket using this `s3` object. When I omit the `region` parameter, then I get the following (expected) error:

```
Error: PermanentRedirect: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
```

So far so good. But sometimes I don't know the right region for a bucket and would like to query AWS for it. I am aware of the `get_bucket_location` command. But it only returns an empty character vector*:

```r
s3$get_bucket_location(Bucket = "my-bucket-name")
$LocationConstraint
character(0)
```

I was expecting to see `us-west-2` - was I mistaken?
As always, many thanks for making this great package available!

*This result is independent of whether I include the `region = 'us-west-2'` element in the `s3()` config argument or not.

**Comment by davidkretch** [comment]
Sorry about that.  That is a bug that we will fix soon.  Thank you for letting us know!

**Comment by davidkretch** [comment]
Hello, sorry for the delay on this.  The next version of Paws will support this.  It will be on CRAN in a couple weeks.  The release date is due to rules about how often we can update packages.

In the mean time, you can get the development version of `paws.common` with support for this by first installing the latest version of Paws from CRAN (i.e. `install.packages("paws")` and then getting `paws.common` from GitHub with `remotes::install_github("paws-r/paws/paws.common")`.

**Comment by tomsing1** [comment]
Many thanks - works great! 👍
