### ISSUE TITLE
Exception handling in PAWS?

### ISSUE THREAD

**Issue by JakeRuss** [paws-r/paws#278]
Hi @davidkretch and @adambanker, 

Thank you for your work on this collection of AWS/R tools. I have taken over as maintainer of another R package which used to rely on the {aws.s3} package and I have been able to successfully convert my fork of that project to use {paws} instead. 

One thing I am not clear on, after reading these docs, is whether paws has exception handling built-in? 

For example, {aws.s3} used an API call to put objects on S3 and I would occasionally encounter situations where those calls resulted in 500 errors. Since that project did not handle that case and automatically re-try the upload, I'd have to re-start the data load from the beginning.

Should my fork of that project handle this case?

**Comment by davidkretch** [comment]
Thanks!  It probably should handle that case.  Eventually I think we'd like to have some kind of automatic retry, but I think it's a ways off sorry to say.

You can now check for specific kinds of errors due to a really nice update by @ryanb8.  You can see some example code here: [examples/error_handling.R](https://github.com/paws-r/paws/blob/master/examples/error_handling.R).

By the way, is the package redshiftTools?  We have a section in our readme on related packages; could we add a link to it in our readme?

**Comment by JakeRuss** [comment]
No problem and I appreciate the pointer to a suggested way to do the error handling that will save me quite a bit of time.

Yes, the package is {redshiftTools}. I've used it daily for months and when {aws.s3} went off CRAN I decided to contact Pablo and take over the development. Here is [the new fork](https://github.com/RedOakStrategic/redshiftTools) of that project. Feel free to link us in the README. 

While I have your attention @davidkretch, mind one last Q? Can you help me understand whether paws has a python dependency? The user doesn't see it but I'm curious about under the hood.

**Comment by davidkretch** [comment]
Cool, thank you.  Paws doesn't have a Python dependency or any other language dependency.  That was one of our main goals.

I know of an R package that does give you access to the Python SDK, [botor](https://daroczig.github.io/botor/), but I don't have experience using it.
