### ISSUE TITLE
S3 put_object fails with raw(0) to create empty files

### ISSUE THREAD

**Issue by arunsrinivasan** [paws-r/paws#318]
Hello, thank you for `paws`. I think there's a tiny issue with creating empty files with `put_object`.

```r
# con created with paws::s3(), paws version = 0.1.9
con$put_object(Body=raw(0), Bucket=bucket, Key="path/file.csv"))
```

I'd expect this command to create an empty file. But this currently fails because the function fails in `sign()` due to `request$body` value being assigned `NULL`. This in turn is being fed into `digest::digest()` with `raw=TRUE` that requires values to be character or raw type, which `NULL` isn't. The body value needs to be `raw(0)` instead of `NULL` here.

**Comment by davidkretch** [comment]
Hello, thank you for the bug report and diagnosis! I just put in a bug fix.

This should be on CRAN (in package `paws.common`) in about three weeks, due to restrictions on how frequently a package can update. I'll comment here once it is on CRAN. You can also get the fix now with `devtools::install_github("paws-r/paws/paws.common")`.

**Comment by davidkretch** [comment]
Hey, sorry for the delay! This bug fix is now on CRAN. You can get it by installing the latest `paws.common`. Let us know if you have issues. Thank you!
