### ISSUE TITLE
Cloudyr project

### ISSUE THREAD

**Issue by norquanttech** [paws-r/paws#349]
Hi,
Great project. 
Are you aware there is another project very similar to this one:  cloudyr project https://github.com/cloudyr
Is this a replacement for that project?  This is only for Amazon, is that right?

**Comment by davidkretch** [comment]
Hello, 

Thank you!

Regarding cloudyr, we know about their packages but we're not super familiar with them. We had a couple different design goals, and consequently have some different pros/cons.

We wanted to support all AWS APIs in a single package. Paws has R functions for every AWS API operation. These are automatically generated from AWS API definitions.

Whereas the cloudyr packages support a only one API at a time, only some of the APIs are supported, but I think they try to make it more R friendly. For example I think when you call the S3 package to get a list of objects in a bucket, it might return a data frame.

Ultimately we wanted R to have the ability to use any AWS API, and felt that with our resources it would be more sustainable to support AWS APIs as is, rather than writing more R friendly front ends to one API a time. We think that is a valuable approach, but mostly outside the scope of Paws.

Paws is designed for AWS only. The exception is there are some cloud platforms that support AWS APIs, like Google Cloud Storage supports the S3 API. In that case, you can use Paws with Google Cloud Storage provided you supply the right endpoint, credentials, and region

**Comment by norquanttech** [comment]
Hi David,

Thanks for the explanaton. That sounds great !
Looking forward to following this project.
greets Lars

**Comment by davidkretch** [comment]
Sounds good. Thanks and be safe!
