### ISSUE TITLE
Get region inside a EC2

### ISSUE THREAD

**Issue by zegkreist** [paws-r/paws#427]
Hi! First of all thank you for the amazing package.

I currently have a internal package that is a wrapper of AWS CLI that I use to access some services. I tested some API calls using PAWS and I found that is faster for the use I need.

My local machine has ~/.aws/config set and works like a charm.

I am now testing with Docker inside a EC2 with a role. I will test in AWS Batch later.

The thing is paws cannot find the Region the EC2 is in, and I cannot make it work. So I ask for a little help if possible.

```
> s3 <- paws::s3()
> s3$list_buckets()
Error in get_region(cfgs$credentials$profile) : No region provided
```

I tested some things inside the container:
- If I run ```curl http://169.254.169.254/latest/dynamic/instance-identity/document``` I can see that the metadata has the region
- ```paws.common:::iam_credentials_provide()``` Returned the secret  and id keys
- ```paws.common:::get_instance_metadata()``` Has a return
- ```system('aws sts get-caller-identity')``` returns the assume role Arn
- ```paws.common:::get_container_credentials()``` returns NULL

**Comment by davidkretch** [comment]
Hey, sorry about that! Does the AWS CLI work without specifying region when run in a Docker container?

Right now at least, Paws needs the region specified in either 1) an argument to `paws::s3`, 2) in an environment variable, or 3) in a config file. Unlike IAM roles, it doesn't automatically pick up the region of the instance or container it's running in BUT if that is what the CLI does do, we'll want to correct that.

A workaround (which is admittedly not great) would be to use curl to get the instance region and set that as the region using either the `paws::s3(config = list(region = foo))` syntax or using the AWS_REGION variable.

At least it is getting IAM credentials . It does also make sense that `get_container_credentials` isn't returning anything because that is designed to get credentials for containers running in ECS rather than EC2.

**Comment by zegkreist** [comment]
Hi @davidkretch, thank you for the response.

Yes, AWS CLI is working fine, I`m still using AWS CLI for the list_objects for more than 1000 and its working fine.

I'm using this workaround, the one of the env_var, but I'm using in the entrypoint of the container. Like this:
```
EC2_AVAIL_ZONE=`curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone`
EC2_REGION="`echo \"$EC2_AVAIL_ZONE\" | sed 's/[a-z]$//'`"
export AWS_REGION=$EC2_REGION
``` 
With the env_var exported paws worked. Is it possible to do, in the internals of the package, see if it is inside a EC2 and grab the region that way?

Again, thank you for the package, its amazing.

**Comment by davidkretch** [comment]
Ok, cool. Let me look into how the CLI does it, so we can keep it mostly consistent with the CLI and other SDKs.

One caveat about Paws (currently at least): `list_objects` doesn't automatically fetch all results if the API breaks it up into multiple pages of 1000 results, and you'll need to use either the `Marker` or `ContinuationToken` depending on which `list_objects` you're using.

Glad it is working out otherwise (mostly). Thank you!

**Comment by davidkretch** [comment]
By the way, here is an example paginator function: https://github.com/paws-r/paws/issues/30#issuecomment-731856133. That one assumes the variable is called `NextToken` rather than what S3 uses, but I think the basic idea will work here as well.

**Comment by zegkreist** [comment]
Thank you for the reference @davidkretch.

About this currently ticket, the workaround  is working for me. Do I need to close it?

**Comment by davidkretch** [comment]
You can leave it open -- I need to look into how the other SDKs get region when inside EC2/ECS that Paws doesn't already cover.

**Comment by davidkretch** [comment]
I don't think the other SDKs get region automatically based on instance/container region.
