### ISSUE TITLE
Access AWS WorkDocs with paws?

### ISSUE THREAD

**Issue by mzorko** [paws-r/paws#437]
Hi, 

Is there way to access and manage AWS WorkDocs using paws?

There this option available in older version: 

https://paws-r.github.io/docs/workdocs/

Thanks,
Mislav

Edit: 

It looks like WorkDocs is available in current git version, but it looks like it is not importing paws.common library properly.

![image](https://user-images.githubusercontent.com/51319014/127163483-0efa48a0-d7cd-4a2b-8ee7-548bf84e97a6.png)

**Comment by davidkretch** [comment]
Hey, sorry! Not with the version on CRAN right now. We'll add that next time we update it on CRAN. It's taken a while because of busy-ness and some new CRAN requirements that we need to meet. Maybe 3-4 weeks? :-(

One less-than-ideal workaround is to install the package from GitHub as in `install_github('paws-r/paws/cran/paws.end.user.computing')`. One big caveat: I haven't ever tried this particular service. If you do try it in advance of CRAN, please let us know how it goes.

**Comment by davidkretch** [comment]
I just submitted `paws.end.user.computing` to CRAN. It should be available for download some time this week. Sorry for the delay!

**Comment by davidkretch** [comment]
This is now available on the version of paws on CRAN (0.1.12). Sorry again for the delay.
