### ISSUE TITLE
Not Modified 304 shouldn't be an error

### ISSUE THREAD

**Issue by anthonynorth** [paws-r/paws#462]
Retrieving an object from S3 with `IfNoneMatch` raises an error when _Not Modified (304)_. It appears to be erroring due to the body being empty, which is expected when the object `ETag == IfNoneMatch` param.

``` r
svc <- paws.storage::s3()
response <- svc$get_object(
  Bucket = "<bucket>",
  Key = "<key>",
  IfNoneMatch = "<etag>"
)
#> Error: SerializationError (HTTP 304). failed to read from query HTTP response body
```

<sup>Created on 2021-10-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DyfanJones** [comment]
I believe the behaviour is working as expected. In the documentation (https://www.paws-r-sdk.com/docs/s3_get_object/)

> IfNoneMatch
Return the object only if its entity tag (ETag) is different from the one specified in this header; otherwise, return a ⁠304 Not Modified⁠ error.


Here is an example from `boto3`

```python
import boto3

client = boto3.Session(profile_name = "paws").client("s3")

resp = client.get_object(
  Bucket = "<bucket>",
  Key = "<key>",
  IfNoneMatch = "<etag>"
)

ClientError: An error occurred (304) when calling the GetObject operation: Not Modified
Cell In[7], line 1
----> 1 resp = client.get_object(
      2   Bucket = "<bucket>", 
      3   Key = "<key>",
      4   IfNoneMatch = "<etag>"
      5 )
Show Traceback
```

Paws equivalent:
``` r
library(paws)

client <- s3(config(credentials(profile = "paws")))

resp <- client$get_object(
  Bucket = "<bucket>",
  Key = "<key>",
  IfNoneMatch = "<etag>"
)
#> Error: SerializationError (HTTP 304). An error occurred (304) when calling the GetObject operation: Not Modified
```

<sup>Created on 2024-07-03 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

I agree this doesn't feel correct as HTTP 304 shouldn't really be an error however it appears AWS want it to be raised as an error. We are just mimicking the other SDKs.
