### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by wlandau** [paws-r/paws#484]
@davidkretch, you mentioned that you and @adambanker are looking for a new maintainer of `paws`. Starting a thread for this.

**Comment by davidkretch** [comment]
Right, thanks @wlandau.  We'll be putting together some documentation soon.

**Comment by DyfanJones** [comment]
Hi @wlandau and @davidkretch,

I am happy to become a maintainer for paws. I am still getting to grips with the backend of the SDK. Any maintainers documentation would be really useful. 

Ideally I would like a co-maintainer to help review PRs and ensure everything is kept to the current standards @davidkretch  and @adambanker have enstablished. @davidkretch will you and @adambanker be still maintaining this going forward or would it be more hands off approach 😄 

I have a few packages dependent on paws (noctua, sagemaker etc... ) and would like to keep the features of paws coming in (for my own selfish reasons 😛).

**Comment by davidkretch** [comment]
Awesome, that would great! So Adam and I are pretty hands off by necessity nowadays, but I will put together documentation for you and will work with you to make sure everything makes sense, works, can review some pull requests, etc. I haven’t been able to do that recently obviously due to a job change and a move but want to help however I can, eg review the latest PR. Let me know if that sounds ok!

**Comment by DyfanJones** [comment]
Hi @davidkretch, that sounds great. Congrats on your new job and move hope it is going well. I would be very grateful for any PR reviews as I would like to keep the high standards you and @adambanker have set for the package. Any documentation would be perfect to help me get up to speed with the package etc.
